# ITNETMON Global Telegraf Output to InfluxDB v2
[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = "1s"

[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  token = "A-ET3RVXFIlo6OO6Y7zrUyrCVFMFWTHM4Q9XaSXE5vnhXVbnKJOQdw5rvnW1wzmuS8GMhaXqmqfCKVqDPhgw0Q=="
  organization = "itnetmon"
  bucket = "itnetmon_metrics"
